//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminuser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adminuser()
        {
            this.FuncData = new HashSet<FuncData>();
        }
    
        public int adminuserid { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public Nullable<int> managetype { get; set; }
        public string email { get; set; }
        public string extension { get; set; }
        public string cellPhone { get; set; }
        public string tel { get; set; }
        public Nullable<byte> Resignation { get; set; }
        public Nullable<bool> astatus { get; set; }
        public string allowIP { get; set; }
        public Nullable<int> loginFail { get; set; }
    
        public virtual FuncPlay FuncPlay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncData> FuncData { get; set; }
    }
}
