//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Contact_ID { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Gender { get; set; }
        public string Contact_Tel { get; set; }
        public string Contact_Email { get; set; }
        public string Contact_Text { get; set; }
        public string Contact_IP { get; set; }
        public Nullable<bool> IsProcess { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
