//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncModuleData
    {
        public int FMDID { get; set; }
        public string FMDName { get; set; }
        public string FMDPageName { get; set; }
        public string FMDSummary { get; set; }
        public int FMDIndex { get; set; }
        public byte FMDState { get; set; }
    
        public virtual FuncData FuncData { get; set; }
    }
}
