//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FuncData()
        {
            this.FuncModuleData = new HashSet<FuncModuleData>();
            this.FuncPlay = new HashSet<FuncPlay>();
            this.Adminuser = new HashSet<Adminuser>();
        }
    
        public int FDID { get; set; }
        public string FDName { get; set; }
        public string FDLink { get; set; }
        public int FDParent { get; set; }
        public byte FDSeq { get; set; }
        public byte FDType { get; set; }
        public byte FDState { get; set; }
        public Nullable<int> Menuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncModuleData> FuncModuleData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncPlay> FuncPlay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adminuser> Adminuser { get; set; }
    }
}
