//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoom_CancelPolicy
    {
        public int LandMark_ID { get; set; }
        public Nullable<int> Cancel_0 { get; set; }
        public Nullable<int> Cancel_1 { get; set; }
        public Nullable<int> Cancel_2to3 { get; set; }
        public Nullable<int> Cancel_4to6 { get; set; }
        public Nullable<int> Cancel_7to9 { get; set; }
        public Nullable<int> Cancel_10to13 { get; set; }
        public Nullable<int> Cancel_over14 { get; set; }
        public string Cancel_Note { get; set; }
    }
}
