//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image_M()
        {
            this.Image_R = new HashSet<Image_R>();
        }
    
        public int Image_ID { get; set; }
        public int Member_ID { get; set; }
        public int Merchant_ID { get; set; }
        public Nullable<bool> IsExternalLink { get; set; }
        public string Image_Path { get; set; }
        public string Image_S_Path { get; set; }
        public bool Image_IsIndex { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image_R> Image_R { get; set; }
    }
}
