//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public int Member_ID { get; set; }
        public string Member_Email { get; set; }
        public string Member_Pwd { get; set; }
        public string Member_SiteID { get; set; }
        public bool Member_SiteID_Setting { get; set; }
        public string Member_FirstName { get; set; }
        public string Member_LastName { get; set; }
        public string Member_NickName { get; set; }
        public string Member_PersonalID { get; set; }
        public string Member_Sex { get; set; }
        public string Member_Bir_Y { get; set; }
        public string Member_Bir_M { get; set; }
        public string Member_Bir_D { get; set; }
        public string Member_Tel { get; set; }
        public string Member_Mobile { get; set; }
        public string Member_Country { get; set; }
        public string Member_City { get; set; }
        public string Member_Addr { get; set; }
        public string Member_Level { get; set; }
        public string Member_Last_Gps_X { get; set; }
        public string Member_Last_Gps_Y { get; set; }
        public string Member_Img { get; set; }
        public string Member_Title { get; set; }
        public string Member_Desc { get; set; }
        public int Member_PageView { get; set; }
        public int Count_Article { get; set; }
        public int Count_Trip { get; set; }
        public int Count_Friend { get; set; }
        public int Count_Fans { get; set; }
        public string App_Token { get; set; }
        public System.Guid App_Token_Code { get; set; }
        public string App_Token_Type { get; set; }
        public Nullable<System.DateTime> App_Token_Date { get; set; }
        public string Web_SessionID { get; set; }
        public string Web_SessionDate { get; set; }
        public string DefaultLang { get; set; }
        public bool IsLock { get; set; }
        public Nullable<System.DateTime> LockDate { get; set; }
        public string CreateIP { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
