//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberImage_M
    {
        public int MemberImage_ID { get; set; }
        public int Member_ID { get; set; }
        public Nullable<int> Target_T_Obj_ID { get; set; }
        public Nullable<int> Target_L_Obj_ID { get; set; }
        public string Image_Title { get; set; }
        public string Image_Path_90 { get; set; }
        public string Image_Path_120 { get; set; }
        public string Image_Path_170 { get; set; }
        public string Image_Path_M450 { get; set; }
        public string Image_Path_M600 { get; set; }
        public string Image_Path_M1024 { get; set; }
        public string MemberImage_Gps_X { get; set; }
        public string MemberImage_Gps_Y { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
