//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public int Merchant_ID { get; set; }
        public string Merchant_Email { get; set; }
        public string Merchant_Account { get; set; }
        public string Merchant_Pwd { get; set; }
        public string LandMark_Type { get; set; }
        public int LandMark_ID { get; set; }
        public string Merchant_Phone { get; set; }
        public string Merchant_Notifier { get; set; }
        public bool Merchant_IsEnable { get; set; }
        public double Merchant_HotelFee { get; set; }
        public string Merchant_ContractNo { get; set; }
        public Nullable<int> adminsalesid { get; set; }
        public string Pay2go_MerchantID { get; set; }
        public string Pay2go_MerchantHashKey { get; set; }
        public string Pay2go_MerchantIvKey { get; set; }
        public bool Pay2go_IsCreditCard { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
