//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant_Pay2go
    {
        public int Merchant_ID { get; set; }
        public string Pay_MemberUnified { get; set; }
        public string Pay_IDCardDate { get; set; }
        public string Pay_IDCardPlace { get; set; }
        public string Pay_MemberName { get; set; }
        public string Pay_MemberPhone { get; set; }
        public string Pay_ManagerName { get; set; }
        public string Pay_ManagerNameE { get; set; }
        public string Pay_LoginAccount { get; set; }
        public string Pay_ManagerMobile { get; set; }
        public string Pay_ManagerEmail { get; set; }
        public string Pay_MerchantID { get; set; }
        public string Pay_MerchantName { get; set; }
        public string Pay_MerchantNameE { get; set; }
        public string Pay_MerchantWebURL { get; set; }
        public string Pay_MerchantAddrCity { get; set; }
        public string Pay_MerchantAddrArea { get; set; }
        public string Pay_MerchantAddrCode { get; set; }
        public string Pay_MerchantAddr { get; set; }
        public string Pay_NationalE { get; set; }
        public string Pay_CityE { get; set; }
        public int Pay_MerchantType { get; set; }
        public string Pay_BusinessType { get; set; }
        public string Pay_MerchantDesc { get; set; }
        public string Pay_BankCode { get; set; }
        public string Pay_SubBankCode { get; set; }
        public string Pay_BankAccount { get; set; }
        public string Pay_PaymentType { get; set; }
        public string Pay_AgreedFee { get; set; }
        public string Pay_AgreedDay { get; set; }
        public bool Is_PayOpen { get; set; }
    }
}
