//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FLBKEntities : DbContext
    {
        public FLBKEntities()
            : base("name=FLBKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action_D> Action_D { get; set; }
        public virtual DbSet<Action_LM> Action_LM { get; set; }
        public virtual DbSet<Action_M> Action_M { get; set; }
        public virtual DbSet<Action_Type> Action_Type { get; set; }
        public virtual DbSet<adminallowip> adminallowip { get; set; }
        public virtual DbSet<adminip> adminip { get; set; }
        public virtual DbSet<AdminMenu> AdminMenu { get; set; }
        public virtual DbSet<Adminsales> Adminsales { get; set; }
        public virtual DbSet<Adminuser> Adminuser { get; set; }
        public virtual DbSet<App_Banner> App_Banner { get; set; }
        public virtual DbSet<AppMessage> AppMessage { get; set; }
        public virtual DbSet<Article_D> Article_D { get; set; }
        public virtual DbSet<Article_M> Article_M { get; set; }
        public virtual DbSet<Article_Tag> Article_Tag { get; set; }
        public virtual DbSet<Article_Tag_R> Article_Tag_R { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Banner_Type> Banner_Type { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<ClaimTemp> ClaimTemp { get; set; }
        public virtual DbSet<Collect> Collect { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<CustomerService_Data> CustomerService_Data { get; set; }
        public virtual DbSet<DiaryIndexArticle> DiaryIndexArticle { get; set; }
        public virtual DbSet<DiaryIndexTop_Image> DiaryIndexTop_Image { get; set; }
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<Famous_D> Famous_D { get; set; }
        public virtual DbSet<Famous_M> Famous_M { get; set; }
        public virtual DbSet<Follow> Follow { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<FuncData> FuncData { get; set; }
        public virtual DbSet<FuncModuleData> FuncModuleData { get; set; }
        public virtual DbSet<FuncPlay> FuncPlay { get; set; }
        public virtual DbSet<Hotel_Bed> Hotel_Bed { get; set; }
        public virtual DbSet<HotelRoom> HotelRoom { get; set; }
        public virtual DbSet<HotelRoom_CancelPolicy> HotelRoom_CancelPolicy { get; set; }
        public virtual DbSet<HotelRoom_Set> HotelRoom_Set { get; set; }
        public virtual DbSet<Image_M> Image_M { get; set; }
        public virtual DbSet<Image_Navigation> Image_Navigation { get; set; }
        public virtual DbSet<Image_R> Image_R { get; set; }
        public virtual DbSet<IndexBanner> IndexBanner { get; set; }
        public virtual DbSet<LandMark_D> LandMark_D { get; set; }
        public virtual DbSet<LandMark_Estimate> LandMark_Estimate { get; set; }
        public virtual DbSet<LandMark_Facility_Items> LandMark_Facility_Items { get; set; }
        public virtual DbSet<LandMark_Facility_R> LandMark_Facility_R { get; set; }
        public virtual DbSet<LandMark_Icon> LandMark_Icon { get; set; }
        public virtual DbSet<LandMark_M> LandMark_M { get; set; }
        public virtual DbSet<LandMark_S> LandMark_S { get; set; }
        public virtual DbSet<MarketingText> MarketingText { get; set; }
        public virtual DbSet<MemberImage_M> MemberImage_M { get; set; }
        public virtual DbSet<MemberImage_R> MemberImage_R { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Members_D> Members_D { get; set; }
        public virtual DbSet<Merchant> Merchant { get; set; }
        public virtual DbSet<Merchant_Pay2go> Merchant_Pay2go { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Number> Number { get; set; }
        public virtual DbSet<Order_CNumber> Order_CNumber { get; set; }
        public virtual DbSet<Order_Company> Order_Company { get; set; }
        public virtual DbSet<Order_Paymethod> Order_Paymethod { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PV> PV { get; set; }
        public virtual DbSet<PV_Log> PV_Log { get; set; }
        public virtual DbSet<ReturnQuestion> ReturnQuestion { get; set; }
        public virtual DbSet<Share> Share { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tag_Class> Tag_Class { get; set; }
        public virtual DbSet<Tag_D> Tag_D { get; set; }
        public virtual DbSet<Tag_M> Tag_M { get; set; }
        public virtual DbSet<Tag_R> Tag_R { get; set; }
        public virtual DbSet<Tag_Relation> Tag_Relation { get; set; }
        public virtual DbSet<TaiwanCity> TaiwanCity { get; set; }
        public virtual DbSet<TaiwanCity_ZipCode> TaiwanCity_ZipCode { get; set; }
        public virtual DbSet<Trip_D> Trip_D { get; set; }
        public virtual DbSet<Trip_M> Trip_M { get; set; }
        public virtual DbSet<Trip_Unused> Trip_Unused { get; set; }
        public virtual DbSet<TripChoice> TripChoice { get; set; }
        public virtual DbSet<TripChoice_Type> TripChoice_Type { get; set; }
        public virtual DbSet<ArticleReport> ArticleReport { get; set; }
        public virtual DbSet<CustomerService_DataLog> CustomerService_DataLog { get; set; }
        public virtual DbSet<CustomerService_ReplyLog> CustomerService_ReplyLog { get; set; }
        public virtual DbSet<MarketingImg> MarketingImg { get; set; }
        public virtual DbSet<Members_LoginLog> Members_LoginLog { get; set; }
        public virtual DbSet<MessageReport> MessageReport { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Event_Data> Event_Data { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetOrderNumber(string versionid, string cdate)
        {
            var versionidParameter = versionid != null ?
                new ObjectParameter("versionid", versionid) :
                new ObjectParameter("versionid", typeof(string));
    
            var cdateParameter = cdate != null ?
                new ObjectParameter("cdate", cdate) :
                new ObjectParameter("cdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetOrderNumber", versionidParameter, cdateParameter);
        }
    }
}
