//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string OrderID { get; set; }
        public string Order_Type { get; set; }
        public int Order_Amount { get; set; }
        public decimal Order_Price { get; set; }
        public decimal Order_TotalPrice { get; set; }
        public Nullable<int> Room_ID { get; set; }
        public Nullable<System.DateTime> Room_Date { get; set; }
        public Nullable<bool> Room_IsDinner { get; set; }
        public Nullable<bool> Room_IsBreakfast { get; set; }
    }
}
