//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public long PaymentsID { get; set; }
        public string OrderID { get; set; }
        public string S_OrderID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> Paymethod_ID { get; set; }
        public Nullable<int> Paymethod_ID_1_LM { get; set; }
        public string CU_ID { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public bool IsTradableOrder { get; set; }
        public bool IsTransaction { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public System.Guid TransactionCode { get; set; }
        public string Status { get; set; }
        public string User_IP { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> SuccessDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<int> Cancel_adminuserid { get; set; }
        public string Log_Memo { get; set; }
        public string Order_Person { get; set; }
        public string Order_Email { get; set; }
        public string Order_Tel { get; set; }
        public string Order_Phone { get; set; }
        public string CheckIn_Person { get; set; }
        public string CheckIn_Phone { get; set; }
        public string Order_Memo { get; set; }
    }
}
