//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tag_M()
        {
            this.Tag_D = new HashSet<Tag_D>();
            this.Tag_R = new HashSet<Tag_R>();
        }
    
        public int Tag_ID { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public bool IsEnable { get; set; }
        public bool IsOfficial { get; set; }
        public bool IsCheck { get; set; }
        public bool IsRecommend { get; set; }
        public int Style { get; set; }
        public int Count { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateIP { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag_D> Tag_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag_R> Tag_R { get; set; }
    }
}
