//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip_D
    {
        public int Trip_ID { get; set; }
        public int Trip_Day { get; set; }
        public int Trip_Sort { get; set; }
        public int LandMark_ID { get; set; }
        public Nullable<int> Traffic_Mode { get; set; }
    
        public virtual Trip_M Trip_M { get; set; }
    }
}
